version: '2'

services:
  postgresserver:
     image: cftdbpostgres
     restart: always
     ports:
       - 5432
     environment:
       POSTGRES_DB: cftdb
       POSTGRES_USER: cftdb
       POSTGRES_PASSWORD: cftdb
     volumes:
       - ./db/postgresdocker/dbscripts:/docker-entrypoint-initdb.d
     networks:
       - mynetwork

  cftapp:
     image: cftapp
     ports:
       - 5000:80
     build:
       context: ./CFT
       dockerfile: Dockerfile
     links:
       - postgresserver
     command: >
       /bin/bash -c "
         sleep 5;
         dotnet ef database update;
       "
     depends_on:
       - "postgresserver"
     networks:
       - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge